### ISSUE TITLE
Mapping Hand Tracking anchors to input image

### ISSUE THREAD

**Issue by smtabatabaie** [natmlx/NatML#10]
Hi, I'm experimenting with HandPose model and wanted to ask if it is possible to overlay and map the predicted anchors on the input image. I explored the codes but couldn't find how it may be done. Would really appreciate it if you can help me with this.
Thanks

**Comment by olokobayusuf** [comment]
Hey there @smtabatabaie , sorry for the late response on this. The predictor currently doesn't do this, because there's a step we're missing: palm detection to get an ROI in the source image. We'll be adding this model sometime soon (no ETA), and once we do, it should be easy to overlay the anchors in the source image.

**Comment by olokobayusuf** [comment]
Closing for newer issue, #23
